MY_OS_FULL = "CentOS7.4_All_x64"
MY_PACKAGE_NAME = ""
MY_PACKAGE_PATH = ""
MY_JOB_NAME  = ""
FTP_BRANCH_TYPE = ""
FTP_PUT_PKG = ""
FTP_PKG_DIR = ""

def version() {
    return sh(script: 'git rev-parse --short HEAD', returnStdout: true)[0 .. 6]
}

def checkoutCode() {
    script {
        if (BRANCH_NAME.contains(" ")) {
            echo "Branch name ${BRANCH_NAME} with blank space is invalid."
            sh "exit 1"
        }
    }

    sh "pwd && rm -rf ./${BRANCH_NAME}* && ls -a"
    echo 'checkout aladdin-cas'
    echo "current branch: $BRANCH_NAME"
    checkout(
        [
        $class : 'GitSCM',
        branches: scm.branches,
        doGenerateSubmoduleConfigurations: false,
        extensions: [
            [
            $class: 'RelativeTargetDirectory',
            relativeTargetDir: "./${BRANCH_NAME}/aladdin-cas"
            ]
        ],
        submoduleCfg: [],
        userRemoteConfigs: [
            [
            credentialsId: '5d59cd15-9716-4597-b858-6b28996e702c',
            url: 'git@gitlab.aishu.cn:aladdin/content-analysis/aladdin-cas.git'
            ]
        ]
        ])

    dir("${BRANCH_NAME}/aladdin-cas") {
        MY_G_VERSION = version()
    }
}

def globalValues() {
    echo 'job name'
    def job_name_parts = env.JOB_NAME.tokenize('/') as String[]
    MY_JOB_NAME = job_name_parts[0]
    echo "${MY_JOB_NAME}"

    echo 'package path name'
    MY_PACKAGE_PATH = "$WORKSPACE/${BRANCH_NAME}/aladdin-cas"
    echo "${MY_PACKAGE_PATH}"

    echo 'pacakge name'
    MY_PACKAGE_NAME = "${MY_JOB_NAME}-$MY_OS_FULL-${new Date().format('yyyyMMdd-HHmmss')}-$MY_G_VERSION@${BRANCH_NAME}-${env.BUILD_NUMBER}"
    echo "${MY_PACKAGE_NAME}"

    echo 'ftp branch type'
    if (BRANCH_NAME =~ "^Release.*") {
        FTP_BRANCH_TYPE = "Release"
    } else if (BRANCH_NAME =~ "^Feature.*") {
        FTP_BRANCH_TYPE = "Feature"
    } else {
        FTP_BRANCH_TYPE = "develop"
    }
    echo "${FTP_BRANCH_TYPE}"

    echo 'ftp put package cmd'
    FTP_PKG_DIR= "/${FTP_BRANCH_TYPE}/module/ServerPacket/${MY_OS_FULL}/${MY_JOB_NAME}"
    FTP_PUT_PKG = "${MY_PACKAGE_NAME}.tar.gz ${FTP_PKG_DIR}/${MY_PACKAGE_NAME}.tar.gz"
    echo "${FTP_PKG_DIR}"
    echo "${FTP_PUT_PKG}"
}

def checkCodeStyle() {
    dir("${BRANCH_NAME}/aladdin-cas") {
        try{
            sh 'PYTHONPATH=$WORKSPACE/${BRANCH_NAME}/aladdin-cas/src pylint --output-format=parseable --reports=no --ignore=src/zhtools --disable=import-error,no-name-in-module,no-member,missing-docstring src > pylint.out || exit 0'
        }
        finally{
            step([
                $class: 'WarningsPublisher',
                parserConfigurations: [[
                    parserName: 'PYLint',
                    pattern: 'pylint.out'
                ]],
                unstableTotalAll: '20',
                usePreviousBuildAsReference: true
            ])
        }
    }
}

def initServer(){
    dir("${BRANCH_NAME}/aladdin-cas") {
        // sh "ping 127.0.0.1"
        sh 'python3 init/start_init_server.py'
    }
}

def unitTest(){
    dir("${BRANCH_NAME}/aladdin-cas") {
	    sh 'cd unit_test && tar -xzf testdata.tgz'
	    sh 'nohup python3 src/server.py &'
	    sh 'ps aux|grep python3'
        sh 'sleep 120'
        // sh 'ping 127.0.0.1'
	    sh 'PYTHONPATH=$WORKSPACE/${BRANCH_NAME}/aladdin-cas/src python3 setup.py test'
	    sh 'pkill -9 python3'
	    xunit(
	      thresholds: [
		failed(
		  unstableThreshold: '0'
		)
	      ],
	      tools: [
		JUnit(
		  deleteOutputFiles: true,
		  failIfNotNew: true,
		  pattern: 'nose2-junit.xml',
		  skipNoTestFiles: true,
		  stopProcessingIfError: true
		)
	      ]
	    )
	    cobertura(
	      autoUpdateHealth: false,
	      autoUpdateStability: false,
	      coberturaReportFile: 'coverage.xml',
	      failUnhealthy: false,
	      failUnstable: false,
	      maxNumberOfBuilds: 0,
	      onlyStable: false,
	      sourceEncoding: 'UTF_8',
	      zoomCoverageChart: false,
	    )
	    publishCoverage(
	      adapters: [
		coberturaAdapter(
		  path: 'coverage.xml',
		)
	      ],
	      sourceFileResolver: [
		level: 'STORE_ALL_BUILD'
	      ]
	    )
    }
}

def SecurityCheck(){
    withDockerContainer(args: "-v ${WORKSPACE}/${BRANCH_NAME}/aladdin-cas:/aladdin-cas", image: "acr.aishu.cn/ict/cobra:latest") {
        sh "python /code/cobra.py -t /aladdin-cas/src -f xml -o /aladdin-cas/cobra.xml"
    }
}

def buildBinaryInitPackage(parameters) {
    switch(parameters){
        case ".x86":
            dir("${BRANCH_NAME}/aladdin-cas") {
                sh 'ls -a '
                sh 'pwd'
                sh 'curl -X DELETE "http://aladdin-cas-milvus:19121/collections/face_recognition" -H "accept: application/json"'
                sh 'curl -X DELETE "http://aladdin-cas-milvus:19121/collections/object_detection" -H "accept: application/json"'
                sh 'cd init && sh package.sh'
                sh 'init/dist/aladdin-cas-init/aladdin-cas-init'
            }
            break
        case ".arm":
            dir("${BRANCH_NAME}/aladdin-cas") {
                sh 'ls -a '
                sh 'pwd'
                sh 'cd init && sh package.sh'
            }
            break
    }
}

def buildBinaryPackage(parameters) {
    switch(parameters){
        case ".x86":
            dir("${BRANCH_NAME}/aladdin-cas") {
                sh 'ls -a '
                sh 'pwd'
                // sh "ping 127.0.0.1"
                sh 'cd src && sh package.sh'
                sh 'nohup src/dist/aladdin-cas/aladdin-cas &'
                sh 'sleep 120'
                sh 'ps aux|grep aladdin-cas'
                // sh 'PYTHONPATH=$(pwd)/src python3 -m unittest -v unit_test/test_api_*.py'
                sh 'pkill -9 aladdin-cas'
            }
            break
        case ".arm":
            dir("${BRANCH_NAME}/aladdin-cas") {
                sh 'ls -a '
                sh 'pwd'
                sh 'cd src && sh package.sh'
            }
            break
    } 
}

def buildCentosPackage() {
    dir("${BRANCH_NAME}/aladdin-cas") {
	sh 'mkdir -p aladdin-cas_service && cp -rp src/dist/aladdin-cas aladdin-cas_service/bin'
	sh 'cp -rp scripts/centos/env.conf aladdin-cas_service'
	sh 'mkdir -p ${MY_PACKAGE_NAME}/app && mv aladdin-cas_service ${MY_PACKAGE_NAME}/app'
	sh 'tar -czvf ${MY_PACKAGE_NAME}.tar.gz ${MY_PACKAGE_NAME}'
    }
}

def buildDockerImage() {
    dir("${BRANCH_NAME}/aladdin-cas") {
	sh 'cd scripts/docker_package && sh build.sh'
    sh 'cd scripts/docker_package && sh build.sh init'
    }
}

def pushDockerImage(parameters){
    switch(parameters){
        case ".x86":
            dir("${WORKSPACE}") {
                script {
                    dockerRegistryUrl = "acr.aishu.cn"
                }
                withCredentials([[
                    $class: 'UsernamePasswordMultiBinding',
                    credentialsId: 'DOCKER_HUB_ACR',
                    usernameVariable: 'DOCKER_HUB_USER',
                    passwordVariable: 'DOCKER_HUB_PASSWORD'
                ]]) {
                    echo "push镜像到harbor"
                    sh """
                    docker tag aladdin-cas:latest ${dockerRegistryUrl}/ict/aladdin-cas:${BRANCH_NAME}
                    docker tag aladdin-cas-init:latest ${dockerRegistryUrl}/ict/aladdin-cas-init:${BRANCH_NAME}
                    docker tag aladdin-cas:latest ${dockerRegistryUrl}/ict/aladdin-cas:${BRANCH_NAME}.${env.BUILD_ID}
                    docker tag aladdin-cas-init:latest ${dockerRegistryUrl}/ict/aladdin-cas-init:${BRANCH_NAME}.${env.BUILD_ID}

                    docker login ${dockerRegistryUrl} -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWORD}
                    docker push ${dockerRegistryUrl}/ict/aladdin-cas:${BRANCH_NAME}
                    docker push ${dockerRegistryUrl}/ict/aladdin-cas-init:${BRANCH_NAME}
                    docker push ${dockerRegistryUrl}/ict/aladdin-cas:${BRANCH_NAME}.${env.BUILD_ID}
                    docker push ${dockerRegistryUrl}/ict/aladdin-cas-init:${BRANCH_NAME}.${env.BUILD_ID}

                    """
                }
            }
            break
        case ".arm":
            dir("${WORKSPACE}") {
                script {
                    dockerRegistryUrl = "acr-arm.aishu.cn"
                }
                withCredentials([[
                    $class: 'UsernamePasswordMultiBinding',
                    credentialsId: 'DOCKER_HUB_ACR',
                    usernameVariable: 'DOCKER_HUB_USER',
                    passwordVariable: 'DOCKER_HUB_PASSWORD'
                ]]) {
                    echo "push镜像到harbor"
                    sh """
                    docker tag aladdin-cas:latest ${dockerRegistryUrl}/ict/aladdin-cas:${BRANCH_NAME}
                    docker tag aladdin-cas-init:latest ${dockerRegistryUrl}/ict/aladdin-cas-init:${BRANCH_NAME}
                    docker tag aladdin-cas:latest ${dockerRegistryUrl}/ict/aladdin-cas:${BRANCH_NAME}.${env.BUILD_ID}
                    docker tag aladdin-cas-init:latest ${dockerRegistryUrl}/ict/aladdin-cas-init:${BRANCH_NAME}.${env.BUILD_ID}

                    docker login ${dockerRegistryUrl} -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWORD}
                    docker push ${dockerRegistryUrl}/ict/aladdin-cas:${BRANCH_NAME}
                    docker push ${dockerRegistryUrl}/ict/aladdin-cas-init:${BRANCH_NAME}
                    docker push ${dockerRegistryUrl}/ict/aladdin-cas:${BRANCH_NAME}.${env.BUILD_ID}
                    docker push ${dockerRegistryUrl}/ict/aladdin-cas-init:${BRANCH_NAME}.${env.BUILD_ID}
                    """
                }
            }
            break
    }
    
}

def dockerBuild(parameters) {
    switch(parameters){
        case ".x86":
            sh 'docker pull acr.aishu.cn/ict/aladdin-cas-base:X86'
            withDockerRegistry([url: 'acr.aishu.cn']) {
                withDockerContainer(args: "--privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/JFR/deps_code/${BRANCH_NAME}:$WORKSPACE/platform:rw --link aladdin-cas-mongo:aladdin-cas-mongo --link aladdin-cas-mysql:aladdin-cas-mysql --link aladdin-cas-milvus:aladdin-cas-milvus --link dl-inference-server:dl-inference-server --link aladdin-cas-es:aladdin-cas-es -e WORKSPACE=$WORKSPACE -e MY_PACKAGE_NAME=$MY_PACKAGE_NAME -e MAX_MEM_USE=100Gi -e mongo_host=aladdin-cas-mongo -e mysql_host=aladdin-cas-mysql -e milvus_host=aladdin-cas-milvus -e tfserving_host=dl-inference-server -e es_host=aladdin-cas-es -e WORKER_PROCESSES=1 -e config_path='./src/server.conf'", image: "acr.aishu.cn/ict/aladdin-cas-base:x86") {  
                    checkCodeStyle()
                    initServer()
                    unitTest()
                    buildBinaryInitPackage(".x86")
                    buildBinaryPackage(".x86")
                    buildCentosPackage()
                    buildDockerImage()
                }
            }
            break

        case ".arm":
                sh 'docker pull acr-arm.aishu.cn/ict/aladdin-cas-base:forarm'
                withDockerRegistry([url: 'acr-arm.aishu.cn']) {
                    withDockerContainer(args: "--privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/JFR/deps_code/${BRANCH_NAME}:$WORKSPACE/platform:rw --link aladdin-cas-mongo:aladdin-cas-mongo --link aladdin-cas-mysql:aladdin-cas-mysql --link aladdin-cas-milvus:aladdin-cas-milvus --link dl-inference-server:dl-inference-server -e WORKSPACE=$WORKSPACE -e MY_PACKAGE_NAME=$MY_PACKAGE_NAME -e MAX_MEM_USE=100Gi -e mongo_host=aladdin-cas-mongo -e mysql_host=aladdin-cas-mysql -e milvus_host='10.2.185.84' -e tfserving_host=dl-inference-server -e WORKER_PROCESSES=1 -e config_path='./src/server.conf'", image: "acr-arm.aishu.cn/ict/aladdin-cas-base:forarm") {  
                        checkCodeStyle()
                        // initServer()
                        // unitTest()
                        buildBinaryInitPackage(".arm")
                        buildBinaryPackage(".arm")
                        buildCentosPackage()
                        buildDockerImage()
                    }
                }
            break
    }
    
}

def uploadReport(parameters){
    switch(parameters){
        case "master":
            MY_JOB_NAME = 'aladdin-cas'
            // stage 'Upload Metrix Report'
            dir("${WORKSPACE}/${BRANCH_NAME}/aladdin-cas") {
                sh 'ls -al'
                ftpPublisher alwaysPublishFromMaster: false, 
                continueOnError: false, 
                failOnError: false, 
                publishers: [
                    [configName: 'FTP_ICT_REPORT', 
                        transfers: [
                            [
                                asciiMode: false, 
                                cleanRemote: false, excludes: '', 
                                flatten: false, 
                                makeEmptyDirs: false, 
                                noDefaultExcludes: false, 
                                patternSeparator: '[, ]+', 
                                remoteDirectory: "/report/${MY_JOB_NAME}/${new Date().format('yyyyMMdd-HHmmss')}-${BUILD_NUMBER}", 
                                remoteDirectorySDF: false, 
                                sourceFiles: "coverage.xml,cobra.xml,nose2-junit.xml,pylint.out"
                            ]
                        ], 
                        usePromotionTimestamp: false, 
                        useWorkspaceInPromotion: false, 
                        verbose: true
                    ]
                ]
            }
            build job: 'M_JenkinsMetrix', parameters: [string(name: 'subsystem', value: 'Aladdin')], propagate: false, wait: false
            break
    }
        
}

def startMysqlServer(parameters){
    switch(parameters){
        case ".x86":
            dir("${WORKSPACE}/${BRANCH_NAME}/aladdin-cas") {
                sh "docker kill aladdin-cas-mysql || echo ' have no container named aladdin-cas-mysql '"
                sh "docker run -d --rm --name aladdin-cas-mysql -e MYSQL_ROOT_PASSWORD=123456 acr.aishu.cn/ict/mysql:5.7"
            }
            withDockerRegistry([url: 'acr.aishu.cn']) {
                withDockerContainer(args: "--privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/JFR/deps_code/AS6.0:$WORKSPACE/platform:rw --link aladdin-cas-mysql:aladdin-cas-mysql -e WORKSPACE=$WORKSPACE ", image: "acr.aishu.cn/ict/mysql:5.7") {
                    dir("${BRANCH_NAME}/aladdin-cas") {
                        sh "sleep 10"
                        // sh "ping 127.0.0.1"
                        sh "mysql -haladdin-cas-mysql -uroot -p123456 < scripts/sql/mysql.sql"
                    }
                }
            }
            break
        case ".arm":
            dir("${WORKSPACE}/${BRANCH_NAME}/aladdin-cas") {
                sh "docker kill aladdin-cas-mysql || echo ' have no container named aladdin-cas-mysql '"
                sh "docker run -d --rm --name aladdin-cas-mysql -e MYSQL_ROOT_PASSWORD=123456 acr.aishu.cn/ict/mariadb:10.4.14"
            }
            withDockerRegistry([url: 'acr.aishu.cn']) {
                withDockerContainer(args: "--privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/JFR/deps_code/AS6.0:$WORKSPACE/platform:rw --link aladdin-cas-mysql:aladdin-cas-mysql -e WORKSPACE=$WORKSPACE ", image: "acr.aishu.cn/ict/mariadb:10.4.14") {
                    dir("${BRANCH_NAME}/aladdin-cas") {
                        sh "sleep 10"
                        sh "mariadb -haladdin-cas-mysql -uroot -p123456 < scripts/sql/mysql.sql"
                    }
                }
            }
            break
    }

}

def startMongoServer(parameters){
    switch(parameters){
        case ".x86":
            dir("${WORKSPACE}/${BRANCH_NAME}/aladdin-cas") {
                sh "docker kill aladdin-cas-mongo || echo 'have no container named aladdin-cas-mongo' "
                sh "docker run -d --rm --name aladdin-cas-mongo acr.aishu.cn/public/mongo:4.2.8"
                //sh "docker run -d --rm --name aladdin-cas-mongo -v ${WORKSPACE}/${BRANCH_NAME}/aladdin-cas/scripts/sql/init_mongo_database.js:/docker-entrypoint-initdb.d/init_mongoDB.js acr.aishu.cn/ict/mongo:4.2.8"
                sh "docker ps -a"
            }
            break
        case ".arm":
            dir("${WORKSPACE}/${BRANCH_NAME}/aladdin-cas") {
                sh "docker kill aladdin-cas-mongo || echo 'have no container named aladdin-cas-mongo' "
                sh "docker run -d --rm --name aladdin-cas-mongo acr.aishu.cn/ict/mongo:4.2.8"
                //sh "docker run -d --rm --name aladdin-cas-mongo -v ${WORKSPACE}/${BRANCH_NAME}/aladdin-cas/scripts/sql/init_mongo_database.js:/docker-entrypoint-initdb.d/init_mongoDB.js acr.aishu.cn/ict/mongo:4.2.8"
                sh "docker ps -a"
            }
            break
    }
}

def startDLInferenceServer(parameters){
    switch(parameters){
        case ".x86":
            dir("${WORKSPACE}/${BRANCH_NAME}/aladdin-cas") {
                sh "docker kill dl-inference-server || echo ' have no container named dl-inference-server '"
                sh "docker run -d --rm --name dl-inference-server acr.aishu.cn/ict/dl-inference-server:Feature-ICT-1467"
                sh "docker ps -a"
            }
            break
        case ".arm":
            dir("${WORKSPACE}/${BRANCH_NAME}/aladdin-cas") {
                sh "docker kill dl-inference-server || echo ' have no container named dl-inference-server '"
                sh "docker run -d --rm --name dl-inference-server acr.aishu.cn/ict/dl-inference-server:forarm"
                sh "docker ps -a"
            }
            break
    }
}

def startMilvusServer(parameters){
    switch(parameters){
        case ".x86":
            dir("${WORKSPACE}/${BRANCH_NAME}/aladdin-cas") {
                sh "docker kill aladdin-cas-milvus || echo 'have no container named aladdin-cas-milvus' "
                sh "docker run -d --rm --name aladdin-cas-milvus acr.aishu.cn/ict/milvus:0.10.0-cpu"
                sh "docker ps -a"
            }
            break
        case ".arm":
            dir("${WORKSPACE}/${BRANCH_NAME}/aladdin-cas") {
                sh "docker kill aladdin-cas-milvus || echo 'have no container named aladdin-cas-milvus' "
                sh "docker run -d --rm --name aladdin-cas-milvus --link aladdin-cas-mysql:aladdin-cas-mysql acr-arm.aishu.cn/ict/milvus:0.10.0-cpu"
                // sh "docker run -d --rm --name aladdin-cas-milvus -v ${WORKSPACE}/${BRANCH_NAME}/aladdin-cas/scripts/conf:/var/lib/milvus/conf --link aladdin-cas-mysql:aladdin-cas-mysql acr-arm.aishu.cn/ict/milvus:0.10.0-cpu"
                sh "sleep 2"
                sh "docker ps -a"
            }
            break
    }
}

def startESServer(parameters){
    switch(parameters){
        case ".x86":
            dir("${WORKSPACE}/${BRANCH_NAME}/aladdin-cas") {
                sh "docker kill aladdin-cas-es || echo 'have no container named aladdin-cas-es' "
                sh 'docker run -d --rm --name aladdin-cas-es -e "discovery.type=single-node" acr.aishu.cn/ict/ai-elasticsearch:5.6.4-1'
                sh "docker ps -a"
            }
            break
        case ".arm":
            dir("${WORKSPACE}/${BRANCH_NAME}/aladdin-cas") {
                sh "docker kill aladdin-cas-es || echo 'have no container named aladdin-cas-es' "
                sh 'docker run -d --rm --name aladdin-cas-es -e "discovery.type=single-node" acr.aishu.cn/ict/ai-elasticsearch:5.6.4-1'
                sh "sleep 2"
                sh "docker ps -a"
            }
            break
    }
}

def clearForeignerServer(){
    sh "docker kill aladdin-cas-milvus || true"
    sh "docker kill aladdin-cas-mongo || true"
    sh "docker kill aladdin-cas-mysql || true"
    sh "docker kill dl-inference-server || true"
    sh "docker kill aladdin-cas-es || true"
}

def delete_docker_image(parameters){
    switch(parameters){
        case ".x86":
            dir("${WORKSPACE}/${BRANCH_NAME}/aladdin-cas") {
                echo "delete .x86 Image"
                sh "docker rmi -f aladdin-cas:latest"
                sh "docker rmi -f aladdin-cas:hua" 
            }
            break
    }
}

pipeline{
    agent none

    stages{
        stage("并行执行"){
            parallel{
                stage("Build Image.x86"){
                    agent{
                        label "docker-builder"
                    }
                    stages{
                        stage("Checkout.x86"){
                            steps{
                                echo "========executing Checkout.x86========"
                                checkoutCode()
                                globalValues()
                                SecurityCheck()
                            }
                        }
                        stage("Init.x86"){
                            steps{
                                echo "========executing Init.x86========"
                                startMysqlServer(".x86")
                                startMilvusServer(".x86")
                                startDLInferenceServer(".x86")
                                startMongoServer(".x86")
                                startESServer(".x86")
                            }
                        }
                        stage("Build.x86"){
                            steps{
                                echo "========executing Build.x86========"
                                dockerBuild(".x86")
                                clearForeignerServer()
                            }
                        }
                        stage("Push.x86"){
                            steps{
                                echo "========executing Push.x86========"
                                pushDockerImage(".x86")
                                uploadReport(BRANCH_NAME)
                            }
                        }
                    }
                    
                }
                stage("Build Image.arm"){
                    agent{
                        label "arm64"
                    }
                    stages{
                        stage("Checkout.arm"){
                            steps{
                                echo "========executing Checkout.arm========"
                                checkoutCode()
                                globalValues()
                                //SecurityCheck()
                            }
                        }
                        stage("Init.arm"){
                            steps{
                                echo "========executing Init.arm========"
                                startMysqlServer(".arm")
                                startMilvusServer(".arm")
                                startDLInferenceServer(".arm")
                                startMongoServer(".arm")
                                startESServer(".arm")
                            }
                        }
                        stage("Build.arm"){
                            steps{
                                echo "========executing Build.arm========"
                                dockerBuild(".arm")
                                clearForeignerServer()
                            }
                        }
                        stage("Push.arm"){
                            steps{
                                echo "========executing Push.arm========"
                                pushDockerImage(".arm")
                            }
                        }
                    }  
                }
            }
        }
    }
}
