apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: fast-text-analysis
  labels:
    app.kubernetes.io/name: fast-text-analysis
    helm.sh/chart: {{ include "fast-text-analysis.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
    {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
    {{- end }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: fast-text-analysis
    app.kubernetes.io/instance: {{ .Release.Name }}
