apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: image-summary
  labels:
    app.kubernetes.io/name: image-summary
    helm.sh/chart: {{ include "image-summary.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
    {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
    {{- end }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: image-summary
    app.kubernetes.io/instance: {{ .Release.Name }}
